/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TrackRouteImport } from './routes/track'
import { Route as TopupRouteImport } from './routes/topup'
import { Route as ThankYouRouteImport } from './routes/thank-you'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as ReviewsRouteImport } from './routes/reviews'
import { Route as QuoteRouteImport } from './routes/quote'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as PortfolioRouteImport } from './routes/portfolio'
import { Route as PackagesRouteImport } from './routes/packages'
import { Route as OrderRouteImport } from './routes/order'
import { Route as InterestRouteImport } from './routes/interest'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as DemoRouteImport } from './routes/demo'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TrackOrderCodeRouteImport } from './routes/track.$orderCode'
import { Route as OrderSuccessRouteImport } from './routes/order.success'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'

const TrackRoute = TrackRouteImport.update({
  id: '/track',
  path: '/track',
  getParentRoute: () => rootRouteImport,
} as any)
const TopupRoute = TopupRouteImport.update({
  id: '/topup',
  path: '/topup',
  getParentRoute: () => rootRouteImport,
} as any)
const ThankYouRoute = ThankYouRouteImport.update({
  id: '/thank-you',
  path: '/thank-you',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const ReviewsRoute = ReviewsRouteImport.update({
  id: '/reviews',
  path: '/reviews',
  getParentRoute: () => rootRouteImport,
} as any)
const QuoteRoute = QuoteRouteImport.update({
  id: '/quote',
  path: '/quote',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const PortfolioRoute = PortfolioRouteImport.update({
  id: '/portfolio',
  path: '/portfolio',
  getParentRoute: () => rootRouteImport,
} as any)
const PackagesRoute = PackagesRouteImport.update({
  id: '/packages',
  path: '/packages',
  getParentRoute: () => rootRouteImport,
} as any)
const OrderRoute = OrderRouteImport.update({
  id: '/order',
  path: '/order',
  getParentRoute: () => rootRouteImport,
} as any)
const InterestRoute = InterestRouteImport.update({
  id: '/interest',
  path: '/interest',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoRoute = DemoRouteImport.update({
  id: '/demo',
  path: '/demo',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TrackOrderCodeRoute = TrackOrderCodeRouteImport.update({
  id: '/$orderCode',
  path: '/$orderCode',
  getParentRoute: () => TrackRoute,
} as any)
const OrderSuccessRoute = OrderSuccessRouteImport.update({
  id: '/success',
  path: '/success',
  getParentRoute: () => OrderRoute,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => BlogRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/blog': typeof BlogRouteWithChildren
  '/contact': typeof ContactRoute
  '/demo': typeof DemoRoute
  '/faq': typeof FaqRoute
  '/interest': typeof InterestRoute
  '/order': typeof OrderRouteWithChildren
  '/packages': typeof PackagesRoute
  '/portfolio': typeof PortfolioRoute
  '/privacy': typeof PrivacyRoute
  '/quote': typeof QuoteRoute
  '/reviews': typeof ReviewsRoute
  '/services': typeof ServicesRoute
  '/terms': typeof TermsRoute
  '/thank-you': typeof ThankYouRoute
  '/topup': typeof TopupRoute
  '/track': typeof TrackRouteWithChildren
  '/blog/$slug': typeof BlogSlugRoute
  '/order/success': typeof OrderSuccessRoute
  '/track/$orderCode': typeof TrackOrderCodeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/blog': typeof BlogRouteWithChildren
  '/contact': typeof ContactRoute
  '/demo': typeof DemoRoute
  '/faq': typeof FaqRoute
  '/interest': typeof InterestRoute
  '/order': typeof OrderRouteWithChildren
  '/packages': typeof PackagesRoute
  '/portfolio': typeof PortfolioRoute
  '/privacy': typeof PrivacyRoute
  '/quote': typeof QuoteRoute
  '/reviews': typeof ReviewsRoute
  '/services': typeof ServicesRoute
  '/terms': typeof TermsRoute
  '/thank-you': typeof ThankYouRoute
  '/topup': typeof TopupRoute
  '/track': typeof TrackRouteWithChildren
  '/blog/$slug': typeof BlogSlugRoute
  '/order/success': typeof OrderSuccessRoute
  '/track/$orderCode': typeof TrackOrderCodeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/blog': typeof BlogRouteWithChildren
  '/contact': typeof ContactRoute
  '/demo': typeof DemoRoute
  '/faq': typeof FaqRoute
  '/interest': typeof InterestRoute
  '/order': typeof OrderRouteWithChildren
  '/packages': typeof PackagesRoute
  '/portfolio': typeof PortfolioRoute
  '/privacy': typeof PrivacyRoute
  '/quote': typeof QuoteRoute
  '/reviews': typeof ReviewsRoute
  '/services': typeof ServicesRoute
  '/terms': typeof TermsRoute
  '/thank-you': typeof ThankYouRoute
  '/topup': typeof TopupRoute
  '/track': typeof TrackRouteWithChildren
  '/blog/$slug': typeof BlogSlugRoute
  '/order/success': typeof OrderSuccessRoute
  '/track/$orderCode': typeof TrackOrderCodeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/blog'
    | '/contact'
    | '/demo'
    | '/faq'
    | '/interest'
    | '/order'
    | '/packages'
    | '/portfolio'
    | '/privacy'
    | '/quote'
    | '/reviews'
    | '/services'
    | '/terms'
    | '/thank-you'
    | '/topup'
    | '/track'
    | '/blog/$slug'
    | '/order/success'
    | '/track/$orderCode'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/blog'
    | '/contact'
    | '/demo'
    | '/faq'
    | '/interest'
    | '/order'
    | '/packages'
    | '/portfolio'
    | '/privacy'
    | '/quote'
    | '/reviews'
    | '/services'
    | '/terms'
    | '/thank-you'
    | '/topup'
    | '/track'
    | '/blog/$slug'
    | '/order/success'
    | '/track/$orderCode'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/blog'
    | '/contact'
    | '/demo'
    | '/faq'
    | '/interest'
    | '/order'
    | '/packages'
    | '/portfolio'
    | '/privacy'
    | '/quote'
    | '/reviews'
    | '/services'
    | '/terms'
    | '/thank-you'
    | '/topup'
    | '/track'
    | '/blog/$slug'
    | '/order/success'
    | '/track/$orderCode'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  BlogRoute: typeof BlogRouteWithChildren
  ContactRoute: typeof ContactRoute
  DemoRoute: typeof DemoRoute
  FaqRoute: typeof FaqRoute
  InterestRoute: typeof InterestRoute
  OrderRoute: typeof OrderRouteWithChildren
  PackagesRoute: typeof PackagesRoute
  PortfolioRoute: typeof PortfolioRoute
  PrivacyRoute: typeof PrivacyRoute
  QuoteRoute: typeof QuoteRoute
  ReviewsRoute: typeof ReviewsRoute
  ServicesRoute: typeof ServicesRoute
  TermsRoute: typeof TermsRoute
  ThankYouRoute: typeof ThankYouRoute
  TopupRoute: typeof TopupRoute
  TrackRoute: typeof TrackRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/track': {
      id: '/track'
      path: '/track'
      fullPath: '/track'
      preLoaderRoute: typeof TrackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/topup': {
      id: '/topup'
      path: '/topup'
      fullPath: '/topup'
      preLoaderRoute: typeof TopupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/thank-you': {
      id: '/thank-you'
      path: '/thank-you'
      fullPath: '/thank-you'
      preLoaderRoute: typeof ThankYouRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reviews': {
      id: '/reviews'
      path: '/reviews'
      fullPath: '/reviews'
      preLoaderRoute: typeof ReviewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quote': {
      id: '/quote'
      path: '/quote'
      fullPath: '/quote'
      preLoaderRoute: typeof QuoteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portfolio': {
      id: '/portfolio'
      path: '/portfolio'
      fullPath: '/portfolio'
      preLoaderRoute: typeof PortfolioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/packages': {
      id: '/packages'
      path: '/packages'
      fullPath: '/packages'
      preLoaderRoute: typeof PackagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/order': {
      id: '/order'
      path: '/order'
      fullPath: '/order'
      preLoaderRoute: typeof OrderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/interest': {
      id: '/interest'
      path: '/interest'
      fullPath: '/interest'
      preLoaderRoute: typeof InterestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo': {
      id: '/demo'
      path: '/demo'
      fullPath: '/demo'
      preLoaderRoute: typeof DemoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/track/$orderCode': {
      id: '/track/$orderCode'
      path: '/$orderCode'
      fullPath: '/track/$orderCode'
      preLoaderRoute: typeof TrackOrderCodeRouteImport
      parentRoute: typeof TrackRoute
    }
    '/order/success': {
      id: '/order/success'
      path: '/success'
      fullPath: '/order/success'
      preLoaderRoute: typeof OrderSuccessRouteImport
      parentRoute: typeof OrderRoute
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof BlogRoute
    }
  }
}

interface BlogRouteChildren {
  BlogSlugRoute: typeof BlogSlugRoute
}

const BlogRouteChildren: BlogRouteChildren = {
  BlogSlugRoute: BlogSlugRoute,
}

const BlogRouteWithChildren = BlogRoute._addFileChildren(BlogRouteChildren)

interface OrderRouteChildren {
  OrderSuccessRoute: typeof OrderSuccessRoute
}

const OrderRouteChildren: OrderRouteChildren = {
  OrderSuccessRoute: OrderSuccessRoute,
}

const OrderRouteWithChildren = OrderRoute._addFileChildren(OrderRouteChildren)

interface TrackRouteChildren {
  TrackOrderCodeRoute: typeof TrackOrderCodeRoute
}

const TrackRouteChildren: TrackRouteChildren = {
  TrackOrderCodeRoute: TrackOrderCodeRoute,
}

const TrackRouteWithChildren = TrackRoute._addFileChildren(TrackRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  BlogRoute: BlogRouteWithChildren,
  ContactRoute: ContactRoute,
  DemoRoute: DemoRoute,
  FaqRoute: FaqRoute,
  InterestRoute: InterestRoute,
  OrderRoute: OrderRouteWithChildren,
  PackagesRoute: PackagesRoute,
  PortfolioRoute: PortfolioRoute,
  PrivacyRoute: PrivacyRoute,
  QuoteRoute: QuoteRoute,
  ReviewsRoute: ReviewsRoute,
  ServicesRoute: ServicesRoute,
  TermsRoute: TermsRoute,
  ThankYouRoute: ThankYouRoute,
  TopupRoute: TopupRoute,
  TrackRoute: TrackRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
