-- Automatic quotation fields for the public quote flow.
ALTER TABLE public.quotes
  ADD COLUMN IF NOT EXISTS quote_number TEXT,
  ADD COLUMN IF NOT EXISTS total_amount NUMERIC(12, 2),
  ADD COLUMN IF NOT EXISTS delivery_days INTEGER,
  ADD COLUMN IF NOT EXISTS estimated_delivery_date DATE,
  ADD COLUMN IF NOT EXISTS breakdown JSONB DEFAULT '{}'::jsonb;

CREATE UNIQUE INDEX IF NOT EXISTS quotes_quote_number_unique
  ON public.quotes (quote_number)
  WHERE quote_number IS NOT NULL;

COMMENT ON COLUMN public.quotes.quote_number IS 'Human-readable quotation reference generated by the website';
COMMENT ON COLUMN public.quotes.total_amount IS 'Automatically calculated quotation total in THB';
COMMENT ON COLUMN public.quotes.delivery_days IS 'Estimated business days from complete project information';
COMMENT ON COLUMN public.quotes.estimated_delivery_date IS 'Estimated delivery date calculated by the website';
COMMENT ON COLUMN public.quotes.breakdown IS 'Structured package, add-on, total, and delivery calculation';
